services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  apiratelimiter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apiratelimiter
    ports:
      - "8080:8080"
    depends_on:
      - redis
